---
- name: Backend app
  hosts: backend
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "14"
  tasks:
    - name: Install GPG
      tags: nodejs, install, setup
      apt:
        name: gnupg
        update_cache: yes
        state: present
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    - name: Clone YOLO Backend repository
      git:
        repo: https://github.com/gichangi/yolo.git
        dest: /home/vagrant/yolo/
        clone: yes
        force: yes
        update: yes
    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=present

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
      
    - name: Install dependencies from lockfile
      tags: app, build, deploy
      shell: npm install
      args:
        chdir: /home/vagrant/yolo/backend/
    - name: Start App
      tags: app, build, deploy
      shell: forever --minUptime 5000 --spinSleepTime 20000 start -c "npm start" server.js
      args:
        chdir: /home/vagrant/yolo/backend/