apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendservice
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /backendservice/?(.*)
            pathType: Prefix
            backend:
              service:
                name: backendservice
                port:
                  number: 5000
