---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  selector:
    app: frontendapp
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer