---
- name: Frontend app
  hosts: frontend
  gather_facts: yes
  become: yes
  remote_user: vagrant
  vars:
    NODEJS_VERSION: "14"
    volumes: "- yolovol:/var/lib/docker/volumes/yolovol/_data"
    frontend_image: "ip2_backend_image:1.0.0"
    frontend_port: "3000"
  roles:
    - frontend

- name: Backend app
  hosts: backend
  gather_facts: yes
  become: yes
  remote_user: vagrant
  vars:
    NODEJS_VERSION: "14"
  roles:
    - backend